#!/usr/bin/env bash
# Display information about subdomains.

domain_information() {
    local line
    line=$(dig "$2"."$1" +short)
    local record=$(echo "$line" | awk '{print $1}')
    local target=$(echo "$line" | awk '{print $2}')
    echo "The subdomain $2 is a $record record and points to $target"
}

if [ "$#" -eq 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
fi
i
